ruby_on_rails/app_demo/config/routes.rb
Rails.application.routes.draw do
  resources :saches
  get "/" => "home#index"
  get 'home/top'
  get "about" => "home#about"
  # get"/sach" => "saches#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

ruby_on_rails/app_demo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ruby_on_rails/app_demo/app/models/sach.rb
class Sach < ApplicationRecord
end

ruby_on_rails/app_demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby_on_rails/app_demo/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def top
  end

  def about
  end
end

ruby_on_rails/app_demo/app/controllers/saches_controller.rb
class SachesController < ApplicationController
  before_action :set_sach, only: %i[ show edit update destroy ]

  # GET /saches or /saches.json
  def index
    @saches208 = Sach.all
  end

  # GET /saches/1 or /saches/1.json
  def show
  end

  # GET /saches/new
  def new
    @sach208 = Sach.new
  end

  # GET /saches/1/edit
  def edit
  end

  # POST /saches or /saches.json
  def create
    @sach208 = Sach.new(sach_params)

    respond_to do |format|
      if @sach208.save
        format.html { redirect_to sach_url(@sach208), notice: "Sach was successfully created." }
        format.json { render :show, status: :created, location: @sach208 }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sach208.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saches/1 or /saches/1.json
  def update
    respond_to do |format|
      if @sach208.update(sach_params)
        format.html { redirect_to sach_url(@sach208), notice: "Sach was successfully updated." }
        format.json { render :show, status: :ok, location: @sach208 }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sach208.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saches/1 or /saches/1.json
  def destroy
    @sach208.destroy

    respond_to do |format|
      format.html { redirect_to saches_url, notice: "Sach was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sach
      @sach208 = Sach.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sach_params
      params.require(:sach).permit(:stt, :ma_hs, :ho_va_ten, :lop, :ma_sach, :ten_sach, :ten_tac_gia, :tu_sach, :so_bm, :ngay_muon, :ngay_tra, :so_ngay, :ghi_chu)
    end
end

ruby_on_rails/app_demo/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_on_rails/app_demo/app/helpers/home_helper.rb
module HomeHelper
end

ruby_on_rails/app_demo/app/helpers/saches_helper.rb
module SachesHelper
end

ruby_on_rails/app_demo/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "Danh sach sach", saches_path, class:"nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

ruby_on_rails/app_demo/app/views/home/top.html.erb
# <h1>Home#top</h1>
# <p>Find me in app/views/home/top.html.erb</p>
<div class="main top-main">
  <div class="top-message">
    <h2>UPDATE VIEW</h2>
    <p>Change contence in top.html file</p>
  </div>
</div>

ruby_on_rails/app_demo/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>App demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
  <%= render 'home/header' %>
  <div class="container">
    <br/>
    <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

ruby_on_rails/app_demo/app/views/saches/_form.html.erb
<%= form_with(model: sach) do |form| %>
  <% if sach.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sach.errors.count, "error") %> prohibited this sach from being saved:</h2>

      <ul>
        <% sach.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :stt, style: "display: block" %>
    <%= form.number_field :stt %>
  </div>

  <div>
    <%= form.label :ma_hs, style: "display: block" %>
    <%= form.text_field :ma_hs %>
  </div>

  <div>
    <%= form.label :ho_va_ten, style: "display: block" %>
    <%= form.text_field :ho_va_ten %>
  </div>

  <div>
    <%= form.label :lop, style: "display: block" %>
    <%= form.text_field :lop %>
  </div>

  <div>
    <%= form.label :ma_sach, style: "display: block" %>
    <%= form.text_field :ma_sach %>
  </div>

  <div>
    <%= form.label :ten_sach, style: "display: block" %>
    <%= form.text_field :ten_sach %>
  </div>

  <div>
    <%= form.label :ten_tac_gia, style: "display: block" %>
    <%= form.text_field :ten_tac_gia %>
  </div>

  <div>
    <%= form.label :tu_sach, style: "display: block" %>
    <%= form.text_field :tu_sach %>
  </div>

  <div>
    <%= form.label :so_bm, style: "display: block" %>
    <%= form.text_field :so_bm %>
  </div>

  <div>
    <%= form.label :ngay_muon, style: "display: block" %>
    <%= form.date_field :ngay_muon %>
  </div>

  <div>
    <%= form.label :ngay_tra, style: "display: block" %>
    <%= form.date_field :ngay_tra %>
  </div>

  <div>
    <%= form.label :so_ngay, style: "display: block" %>
    <%= form.number_field :so_ngay %>
  </div>

  <div>
    <%= form.label :ghi_chu, style: "display: block" %>
    <%= form.text_field :ghi_chu %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

ruby_on_rails/app_demo/app/views/saches/_sach.html.erb
<div id="<%= dom_id sach %>">
  <p>
    <strong>Stt:</strong>
    <%= sach.stt %>
  </p>

  <p>
    <strong>Ma hs:</strong>
    <%= sach.ma_hs %>
  </p>

  <p>
    <strong>Ho va ten:</strong>
    <%= sach.ho_va_ten %>
  </p>

  <p>
    <strong>Lop:</strong>
    <%= sach.lop %>
  </p>

  <p>
    <strong>Ma sach:</strong>
    <%= sach.ma_sach %>
  </p>

  <p>
    <strong>Ten sach:</strong>
    <%= sach.ten_sach %>
  </p>

  <p>
    <strong>Ten tac gia:</strong>
    <%= sach.ten_tac_gia %>
  </p>

  <p>
    <strong>Tu sach:</strong>
    <%= sach.tu_sach %>
  </p>

  <p>
    <strong>So bm:</strong>
    <%= sach.so_bm %>
  </p>

  <p>
    <strong>Ngay muon:</strong>
    <%= sach.ngay_muon %>
  </p>

  <p>
    <strong>Ngay tra:</strong>
    <%= sach.ngay_tra %>
  </p>

  <p>
    <strong>So ngay:</strong>
    <%= sach.so_ngay %>
  </p>

  <p>
    <strong>Ghi chu:</strong>
    <%= sach.ghi_chu %>
  </p>

</div>

ruby_on_rails/app_demo/app/views/saches/edit.html.erb
<h1>Editing sach</h1>

<%= render "form", sach: @sach208 %>

<br>

<div>
  <%= link_to "Xem sach", @sach208 %> |
  <%= link_to "Danh sach sach", saches_path %>
</div>

ruby_on_rails/app_demo/app/views/saches/index.html.erb
<div class="px-4">
        <div class="d-flex justify-conten-start">
          <h1 class="text-success fs-4 d-flex flex-column align-items-center margin-left: 100px">
            <span>THƯ VIỆN</span> TRƯỜNG TIỂU HỌC PHONG THẠNH TÂY A
          </h1>
        </div>
        <div class="d-flex align-items-center justify-content-between">
          <h2 class="text-warning">QUẢN LÝ CHO HỌC SINH MƯỢN SÁCH</h2>
          <div class="d-flex align-items-center">
            <p class="text-primary">Quy định ngày quá hạn</p>
            <p class="ms-2 p-3 border border-success">3</p>
          </div>
        </div>
      </div>

<table class="table table-striped table-bordered table-hover">
<thead class="thead-dark">
  <tr>
    <th>STT</th>
    <th>Ma HS</th>
    <th>Ho va ten</th>
    <th>Lop</th>
    <th>Ma sach</th>
    <th>Ten sach</th>
    <th>Ten tac gia</th>
    <th>Tu sach</th>
    <th>So BM</th>
    <th>Ngay muon</th>
    <th>Ngay tra</th>
    <th>So ngay</th>
    <th>Ghi chu</th>
    <th>Thao tac</th>
  </tr>
  </thead>
  <tbody>
<% for sach in @saches208 %>
  <tr>
    <td><%=h sach.stt %></td>
    <td><%=h sach.ma_hs %></td>
    <td><%=h sach.ho_va_ten %></td>
    <td><%=h sach.lop %></td>
    <td><%=h sach.ma_sach %></td>
    <td><%=h sach.ten_sach %></td>
    <td><%=h sach.ten_tac_gia %></td>
    <td><%=h sach.tu_sach %></td>
    <td><%=h sach.so_bm %></td>
    <td><%=h sach.ngay_muon %></td>
    <td><%=h sach.ngay_tra %></td>
    <td><%=h sach.so_ngay %></td>
    <td><%=h sach.ghi_chu %></td>
    <td><%= link_to 'Xem', sach %>
    |<%= link_to 'Sua', edit_sach_path(sach) %>
    |<%= link_to 'Xoa', sach, :confirm => 'Are you sure?',
            :method => :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

<%= link_to 'Them sach', new_sach_path(sach) %>

ruby_on_rails/app_demo/app/views/saches/new.html.erb
<h1>New sach</h1>

<%= render "form", sach: @sach208 %>

<br>

<div>
  <%= link_to "Danh sach sach", saches_path %>
</div>

ruby_on_rails/app_demo/app/views/saches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sach208 %>

<div>
  <%= link_to "Chinh sua sach", edit_sach_path(@sach208) %> |
  <%= link_to "Danh sach sach", saches_path %>

  <%= button_to "Xoa sach", @sach208, method: :delete %>
</div>